// server/vehicleData.js

/**
 * Typische Status-Werte:
 * - 'aktiv'    → im Fahrgastbetrieb
 * - 'wartung'  → in Werkstatt / geplant
 * - 'offline'  → keine Verbindung / abgestellt
 *
 * Operatoren in diesem Mock:
 * - Graz Linien
 * - DB Regio BaWü
 * - Agilis
 *
 * VCUs:
 * - vcuCount: Anzahl verbauter VCUs
 * - vcuNumber: "primäre" VCU-Nummer (erste)
 * - vcus: Liste aller VCUs mit Nummer, Position und Online-Status
 */

const vehicles = [
  // ============================================================
  // GRAZ LINIEN – Fahrzeuge 201–204
  // ============================================================
  {
    id: 'GL-201',
    name: 'Graz Linien 201',
    shortNumber: 201,
    fleet: 'Stadler Variobahn',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Linie 4',
    status: 'aktiv',
    location: 'Graz Jakominiplatz',
    gps: { lat: 47.0707, lng: 15.438 },
    lastSeen: '2025-12-11T09:10:00Z',
    softwareVersion: 'v3.2.1',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-11-20',
    nextSoftwareRollout: '2026-03-01',
    nextMaintenance: '2026-01-05',
    maintenanceDepot: 'Remise Steyrergasse',
    buildYear: 2012,
    seats: 70,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-GL-201-01'],
    vcuCount: 2,
    vcuNumber: '20550',
    vcus: [
      { id: 'VCU-GL-201-1', number: '20550', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-GL-201-2', number: '20551', position: 'Triebkopf B', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.4.2' },
      { name: 'Passenger WiFi', firmware: 'v2.9.0' },
    ],
    notes: 'Pilotfahrzeug für WLAN im Innenstadtbereich.'
  },
  {
    id: 'GL-202',
    name: 'Graz Linien 202',
    shortNumber: 202,
    fleet: 'Stadler Variobahn',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Linie 5',
    status: 'aktiv',
    location: 'Graz Hauptbahnhof',
    gps: { lat: 47.073, lng: 15.41 },
    lastSeen: '2025-12-11T09:08:00Z',
    softwareVersion: 'v3.2.1',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-11-22',
    nextSoftwareRollout: '2026-03-02',
    nextMaintenance: '2026-01-08',
    maintenanceDepot: 'Remise Steyrergasse',
    buildYear: 2012,
    seats: 70,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-GL-202-01'],
    vcuCount: 1,
    vcuNumber: '20560',
    vcus: [
      { id: 'VCU-GL-202-1', number: '20560', position: 'Zentralmodul', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.4.2' },
      { name: 'Passenger Info', firmware: 'v1.9.0' },
    ],
    notes: 'Standardfahrzeug mit stabilem Funkempfang.'
  },
  {
    id: 'GL-203',
    name: 'Graz Linien 203',
    shortNumber: 203,
    fleet: 'Stadler Variobahn',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Linie 7',
    status: 'wartung',
    location: 'Werkstätte Steyrergasse',
    gps: { lat: 47.058, lng: 15.449 },
    lastSeen: '2025-12-11T06:00:00Z',
    softwareVersion: 'v3.0.5',
    softwareUpToDate: false,
    lastSoftwareRollout: '2025-03-10',
    nextSoftwareRollout: '2025-12-20',
    nextMaintenance: '2025-12-11',
    maintenanceDepot: 'Remise Steyrergasse',
    buildYear: 2011,
    seats: 70,
    wifiInstalled: false,
    simStatus: 'warn',
    sims: ['SIM-GL-203-01'],
    vcuCount: 2,
    vcuNumber: '20570',
    vcus: [
      { id: 'VCU-GL-203-1', number: '20570', position: 'Triebkopf A', status: 'offline' },
      { id: 'VCU-GL-203-2', number: '20571', position: 'Triebkopf B', status: 'wartung' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.1.0' },
    ],
    notes: 'Wartung inkl. Nachrüstung WLAN und Firmware-Update.'
  },
  {
    id: 'GL-204',
    name: 'Graz Linien 204',
    shortNumber: 204,
    fleet: 'Stadler Variobahn',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Linie 3',
    status: 'aktiv',
    location: 'Graz Andritz',
    gps: { lat: 47.099, lng: 15.43 },
    lastSeen: '2025-12-11T09:12:00Z',
    softwareVersion: 'v3.2.1',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-11-28',
    nextSoftwareRollout: '2026-04-01',
    nextMaintenance: '2026-01-15',
    maintenanceDepot: 'Remise Steyrergasse',
    buildYear: 2013,
    seats: 70,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-GL-204-01'],
    vcuCount: 3,
    vcuNumber: '20580',
    vcus: [
      { id: 'VCU-GL-204-1', number: '20580', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-GL-204-2', number: '20581', position: 'Mittelmodul', status: 'online' },
      { id: 'VCU-GL-204-3', number: '20582', position: 'Triebkopf B', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.4.2' },
      { name: 'Passenger WiFi', firmware: 'v2.9.1' },
      { name: 'Passenger Info', firmware: 'v2.0.0' },
    ],
    notes: 'Referenzfahrzeug für neue Monitoring-Funktionen.'
  },

  // Graz Linien 651–654 (Bus)
  {
    id: 'GL-651',
    name: 'Graz Linien 651',
    shortNumber: 651,
    fleet: 'Mercedes Citaro',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Bus 31',
    status: 'aktiv',
    location: 'Graz Hauptbahnhof',
    gps: { lat: 47.073, lng: 15.41 },
    lastSeen: '2025-12-11T09:03:00Z',
    softwareVersion: 'v3.1.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-10-15',
    nextSoftwareRollout: '2026-03-15',
    nextMaintenance: '2026-01-10',
    maintenanceDepot: 'Busgarage Eggenberg',
    buildYear: 2016,
    seats: 35,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-GL-651-01'],
    vcuCount: 1,
    vcuNumber: '20600',
    vcus: [
      { id: 'VCU-GL-651-1', number: '20600', position: 'Fahrzeugelektronik', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.0' },
      { name: 'Passenger WiFi', firmware: 'v2.8.0' },
    ],
    notes: 'Stadtbus mit hoher Fahrgastfrequenz im Berufsverkehr.'
  },
  {
    id: 'GL-652',
    name: 'Graz Linien 652',
    shortNumber: 652,
    fleet: 'Mercedes Citaro',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Bus 40',
    status: 'aktiv',
    location: 'Graz Don Bosco',
    gps: { lat: 47.052, lng: 15.414 },
    lastSeen: '2025-12-11T08:55:00Z',
    softwareVersion: 'v3.1.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-10-20',
    nextSoftwareRollout: '2026-03-20',
    nextMaintenance: '2026-01-18',
    maintenanceDepot: 'Busgarage Eggenberg',
    buildYear: 2016,
    seats: 35,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-GL-652-01'],
    vcuCount: 2,
    vcuNumber: '20610',
    vcus: [
      { id: 'VCU-GL-652-1', number: '20610', position: 'VCU Front', status: 'online' },
      { id: 'VCU-GL-652-2', number: '20611', position: 'VCU Heck', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.0' },
      { name: 'Passenger Info', firmware: 'v1.8.0' },
    ],
    notes: 'Fahrzeug mit erhöhter Sensorik für Fahrgastzählsysteme.'
  },
  {
    id: 'GL-653',
    name: 'Graz Linien 653',
    shortNumber: 653,
    fleet: 'Mercedes Citaro',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Bus 33',
    status: 'wartung',
    location: 'Busgarage Eggenberg',
    gps: { lat: 47.065, lng: 15.402 },
    lastSeen: '2025-12-11T06:30:00Z',
    softwareVersion: 'v2.9.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2024-12-01',
    nextSoftwareRollout: '2025-12-22',
    nextMaintenance: '2025-12-11',
    maintenanceDepot: 'Busgarage Eggenberg',
    buildYear: 2015,
    seats: 35,
    wifiInstalled: false,
    simStatus: 'warn',
    sims: ['SIM-GL-653-01'],
    vcuCount: 2,
    vcuNumber: '20620',
    vcus: [
      { id: 'VCU-GL-653-1', number: '20620', position: 'VCU Front', status: 'offline' },
      { id: 'VCU-GL-653-2', number: '20621', position: 'VCU Heck', status: 'wartung' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.0.0' },
    ],
    notes: 'Geplante Nachrüstung von WLAN und neuem Gateway.'
  },
  {
    id: 'GL-654',
    name: 'Graz Linien 654',
    shortNumber: 654,
    fleet: 'Mercedes Citaro',
    operator: 'Graz Linien',
    country: 'AT',
    line: 'Bus 52',
    status: 'offline',
    location: 'Abstellplatz Eggenberg',
    gps: { lat: 47.067, lng: 15.399 },
    lastSeen: '2025-12-10T21:10:00Z',
    softwareVersion: 'v2.8.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2024-09-15',
    nextSoftwareRollout: '2026-02-15',
    nextMaintenance: '2026-01-25',
    maintenanceDepot: 'Busgarage Eggenberg',
    buildYear: 2014,
    seats: 35,
    wifiInstalled: false,
    simStatus: 'critical',
    sims: ['SIM-GL-654-01'],
    vcuCount: 1,
    vcuNumber: '20630',
    vcus: [
      { id: 'VCU-GL-654-1', number: '20630', position: 'VCU Front', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v4.8.0' },
    ],
    notes: 'Fahrzeug außer Betrieb; Retrofit ab Q2/26 geplant.'
  },

  // ============================================================
  // DB REGIO BaWü – Fahrzeuge 101–108
  // ============================================================
  {
    id: 'DB-BW-101',
    name: 'DB Regio BaWü 101',
    shortNumber: 101,
    fleet: 'BR 440',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'RB 16',
    status: 'aktiv',
    location: 'Stuttgart Hbf',
    gps: { lat: 48.785, lng: 9.182 },
    lastSeen: '2025-12-11T09:04:00Z',
    softwareVersion: 'v3.2.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-10-10',
    nextSoftwareRollout: '2026-04-10',
    nextMaintenance: '2026-01-12',
    maintenanceDepot: 'Werk Stuttgart',
    buildYear: 2013,
    seats: 220,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-DB-BW-101-01', 'SIM-DB-BW-101-02'],
    vcuCount: 2,
    vcuNumber: '20700',
    vcus: [
      { id: 'VCU-DB-BW-101-1', number: '20700', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-DB-BW-101-2', number: '20701', position: 'Triebkopf B', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.4.0' },
      { name: 'Passenger WiFi', firmware: 'v2.9.0' },
    ],
    notes: 'Pilotfahrzeug für Monitoring im Stuttgarter Netz.'
  },
  {
    id: 'DB-BW-102',
    name: 'DB Regio BaWü 102',
    shortNumber: 102,
    fleet: 'BR 440',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'RB 17',
    status: 'aktiv',
    location: 'Tübingen Hbf',
    gps: { lat: 48.518, lng: 9.058 },
    lastSeen: '2025-12-11T09:06:00Z',
    softwareVersion: 'v3.2.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-10-12',
    nextSoftwareRollout: '2026-04-12',
    nextMaintenance: '2026-01-18',
    maintenanceDepot: 'Werk Stuttgart',
    buildYear: 2013,
    seats: 220,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-DB-BW-102-01'],
    vcuCount: 1,
    vcuNumber: '20710',
    vcus: [
      { id: 'VCU-DB-BW-102-1', number: '20710', position: 'Zentralmodul', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.4.0' },
      { name: 'Passenger Info', firmware: 'v2.0.0' },
    ],
    notes: 'Stabile Verbindung auf der Neckar-Alb-Strecke.'
  },
  {
    id: 'DB-BW-103',
    name: 'DB Regio BaWü 103',
    shortNumber: 103,
    fleet: 'BR 425',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'S1',
    status: 'aktiv',
    location: 'Stuttgart Schwabstraße',
    gps: { lat: 48.769, lng: 9.164 },
    lastSeen: '2025-12-11T09:02:00Z',
    softwareVersion: 'v3.0.5',
    softwareUpToDate: false,
    lastSoftwareRollout: '2025-01-15',
    nextSoftwareRollout: '2025-12-21',
    nextMaintenance: '2026-01-05',
    maintenanceDepot: 'Werk Plochingen',
    buildYear: 2004,
    seats: 180,
    wifiInstalled: false,
    simStatus: 'warn',
    sims: ['SIM-DB-BW-103-01'],
    vcuCount: 2,
    vcuNumber: '20720',
    vcus: [
      { id: 'VCU-DB-BW-103-1', number: '20720', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-DB-BW-103-2', number: '20721', position: 'Triebkopf B', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.0.0' },
    ],
    notes: 'Ältere S-Bahn-Einheit, Retrofit in Planung.'
  },
  {
    id: 'DB-BW-104',
    name: 'DB Regio BaWü 104',
    shortNumber: 104,
    fleet: 'BR 425',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'S2',
    status: 'offline',
    location: 'Abstellanlage Plochingen',
    gps: { lat: 48.711, lng: 9.428 },
    lastSeen: '2025-12-10T23:15:00Z',
    softwareVersion: 'v2.9.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2024-09-01',
    nextSoftwareRollout: '2026-02-01',
    nextMaintenance: '2026-01-22',
    maintenanceDepot: 'Werk Plochingen',
    buildYear: 2003,
    seats: 180,
    wifiInstalled: false,
    simStatus: 'critical',
    sims: ['SIM-DB-BW-104-01'],
    vcuCount: 1,
    vcuNumber: '20730',
    vcus: [
      { id: 'VCU-DB-BW-104-1', number: '20730', position: 'Zentralmodul', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v4.7.0' },
    ],
    notes: 'Derzeit außer Betrieb, Hauptuntersuchung ausstehend.'
  },
  {
    id: 'DB-BW-105',
    name: 'DB Regio BaWü 105',
    shortNumber: 105,
    fleet: 'BR 146 + Dosto',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'RE 5',
    status: 'aktiv',
    location: 'Freiburg (Breisgau) Hbf',
    gps: { lat: 47.9978, lng: 7.841 },
    lastSeen: '2025-12-11T09:07:00Z',
    softwareVersion: 'v3.1.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-09-20',
    nextSoftwareRollout: '2026-03-20',
    nextMaintenance: '2026-01-30',
    maintenanceDepot: 'Werk Freiburg',
    buildYear: 2010,
    seats: 380,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-DB-BW-105-01', 'SIM-DB-BW-105-02'],
    vcuCount: 3,
    vcuNumber: '20740',
    vcus: [
      { id: 'VCU-DB-BW-105-1', number: '20740', position: 'Lok', status: 'online' },
      { id: 'VCU-DB-BW-105-2', number: '20741', position: 'Steuerwagen', status: 'online' },
      { id: 'VCU-DB-BW-105-3', number: '20742', position: 'Mittelwagen', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.0' },
      { name: 'Passenger WiFi', firmware: 'v2.9.0' },
      { name: 'Passenger Info', firmware: 'v2.0.0' },
    ],
    notes: 'Hauptrelation am Oberrhein, hohe Auslastung.'
  },
  {
    id: 'DB-BW-106',
    name: 'DB Regio BaWü 106',
    shortNumber: 106,
    fleet: 'BR 146 + Dosto',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'RE 7',
    status: 'aktiv',
    location: 'Karlsruhe Hbf',
    gps: { lat: 49.009, lng: 8.402 },
    lastSeen: '2025-12-11T09:05:30Z',
    softwareVersion: 'v3.1.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-09-22',
    nextSoftwareRollout: '2026-03-22',
    nextMaintenance: '2026-02-02',
    maintenanceDepot: 'Werk Karlsruhe',
    buildYear: 2011,
    seats: 380,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-DB-BW-106-01'],
    vcuCount: 2,
    vcuNumber: '20750',
    vcus: [
      { id: 'VCU-DB-BW-106-1', number: '20750', position: 'Lok', status: 'online' },
      { id: 'VCU-DB-BW-106-2', number: '20751', position: 'Steuerwagen', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.0' },
      { name: 'Passenger WiFi', firmware: 'v2.9.0' },
    ],
    notes: 'Typischer RE mit stabiler Funkversorgung entlang der Rheinschiene.'
  },
  {
    id: 'DB-BW-107',
    name: 'DB Regio BaWü 107',
    shortNumber: 107,
    fleet: 'BR 1440',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'MEX 16',
    status: 'wartung',
    location: 'Werk Ulm',
    gps: { lat: 48.402, lng: 9.984 },
    lastSeen: '2025-12-11T05:50:00Z',
    softwareVersion: 'v3.0.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2025-02-01',
    nextSoftwareRollout: '2025-12-23',
    nextMaintenance: '2025-12-11',
    maintenanceDepot: 'Werk Ulm',
    buildYear: 2018,
    seats: 230,
    wifiInstalled: true,
    simStatus: 'warn',
    sims: ['SIM-DB-BW-107-01'],
    vcuCount: 2,
    vcuNumber: '20760',
    vcus: [
      { id: 'VCU-DB-BW-107-1', number: '20760', position: 'Triebkopf A', status: 'wartung' },
      { id: 'VCU-DB-BW-107-2', number: '20761', position: 'Triebkopf B', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.1.0' },
      { name: 'Passenger WiFi', firmware: 'v2.7.0' },
    ],
    notes: 'Software-Rollout wird im Rahmen der Wartung eingespielt.'
  },
  {
    id: 'DB-BW-108',
    name: 'DB Regio BaWü 108',
    shortNumber: 108,
    fleet: 'BR 1440',
    operator: 'DB Regio BaWü',
    country: 'DE',
    line: 'MEX 18',
    status: 'aktiv',
    location: 'Heilbronn Hbf',
    gps: { lat: 49.142, lng: 9.22 },
    lastSeen: '2025-12-11T09:09:30Z',
    softwareVersion: 'v3.1.5',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-09-30',
    nextSoftwareRollout: '2026-04-30',
    nextMaintenance: '2026-02-10',
    maintenanceDepot: 'Werk Ulm',
    buildYear: 2019,
    seats: 230,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-DB-BW-108-01', 'SIM-DB-BW-108-02'],
    vcuCount: 3,
    vcuNumber: '20770',
    vcus: [
      { id: 'VCU-DB-BW-108-1', number: '20770', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-DB-BW-108-2', number: '20771', position: 'Mittelwagen', status: 'online' },
      { id: 'VCU-DB-BW-108-3', number: '20772', position: 'Triebkopf B', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.1' },
      { name: 'Passenger WiFi', firmware: 'v2.9.1' },
    ],
    notes: 'Referenzzug für Monitoring im Frankenraum.'
  },

  // ============================================================
  // AGILIS – Fahrzeuge 701–704
  // ============================================================
  {
    id: 'AG-701',
    name: 'agilis 701',
    shortNumber: 701,
    fleet: 'Alstom Coradia Continental',
    operator: 'Agilis',
    country: 'DE',
    line: 'ag 85020',
    status: 'aktiv',
    location: 'Regensburg Hbf',
    gps: { lat: 49.014, lng: 12.099 },
    lastSeen: '2025-12-11T09:01:00Z',
    softwareVersion: 'v3.2.0',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-10-05',
    nextSoftwareRollout: '2026-04-05',
    nextMaintenance: '2026-01-10',
    maintenanceDepot: 'Regensburg',
    buildYear: 2014,
    seats: 180,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-AG-701-01'],
    vcuCount: 2,
    vcuNumber: '20800',
    vcus: [
      { id: 'VCU-AG-701-1', number: '20800', position: 'Triebkopf A', status: 'online' },
      { id: 'VCU-AG-701-2', number: '20801', position: 'Triebkopf B', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.3.0' },
      { name: 'Passenger WiFi', firmware: 'v2.9.0' },
    ],
    notes: 'Pilotstrecke in der Oberpfalz, gute Funkabdeckung.'
  },
  {
    id: 'AG-702',
    name: 'agilis 702',
    shortNumber: 702,
    fleet: 'Alstom Coradia Continental',
    operator: 'Agilis',
    country: 'DE',
    line: 'ag 85024',
    status: 'aktiv',
    location: 'Weiden (Oberpf) Hbf',
    gps: { lat: 49.676, lng: 12.156 },
    lastSeen: '2025-12-11T09:06:00Z',
    softwareVersion: 'v3.1.5',
    softwareUpToDate: true,
    lastSoftwareRollout: '2025-09-25',
    nextSoftwareRollout: '2026-03-25',
    nextMaintenance: '2026-01-22',
    maintenanceDepot: 'Regensburg',
    buildYear: 2015,
    seats: 180,
    wifiInstalled: true,
    simStatus: 'ok',
    sims: ['SIM-AG-702-01'],
    vcuCount: 1,
    vcuNumber: '20810',
    vcus: [
      { id: 'VCU-AG-702-1', number: '20810', position: 'Zentralmodul', status: 'online' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.2.0' },
      { name: 'Passenger Info', firmware: 'v1.9.0' },
    ],
    notes: 'Regelzug im agilis-Netz Oberpfalz.'
  },
  {
    id: 'AG-703',
    name: 'agilis 703',
    shortNumber: 703,
    fleet: 'Alstom Coradia Continental',
    operator: 'Agilis',
    country: 'DE',
    line: 'ag 85030',
    status: 'wartung',
    location: 'Werk Regensburg',
    gps: { lat: 49.022, lng: 12.09 },
    lastSeen: '2025-12-11T05:45:00Z',
    softwareVersion: 'v3.0.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2025-01-10',
    nextSoftwareRollout: '2025-12-25',
    nextMaintenance: '2025-12-11',
    maintenanceDepot: 'Regensburg',
    buildYear: 2013,
    seats: 180,
    wifiInstalled: true,
    simStatus: 'warn',
    sims: ['SIM-AG-703-01'],
    vcuCount: 2,
    vcuNumber: '20820',
    vcus: [
      { id: 'VCU-AG-703-1', number: '20820', position: 'Triebkopf A', status: 'wartung' },
      { id: 'VCU-AG-703-2', number: '20821', position: 'Triebkopf B', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v5.1.0' },
      { name: 'Passenger WiFi', firmware: 'v2.7.0' },
    ],
    notes: 'Software-Update wird im Rahmen der Wartung eingespielt.'
  },
  {
    id: 'AG-704',
    name: 'agilis 704',
    shortNumber: 704,
    fleet: 'Alstom Coradia Continental',
    operator: 'Agilis',
    country: 'DE',
    line: 'ag 85032',
    status: 'offline',
    location: 'Abstellanlage Regensburg',
    gps: { lat: 49.017, lng: 12.095 },
    lastSeen: '2025-12-10T22:15:00Z',
    softwareVersion: 'v2.9.0',
    softwareUpToDate: false,
    lastSoftwareRollout: '2024-08-20',
    nextSoftwareRollout: '2026-02-20',
    nextMaintenance: '2026-01-28',
    maintenanceDepot: 'Regensburg',
    buildYear: 2012,
    seats: 180,
    wifiInstalled: false,
    simStatus: 'critical',
    sims: ['SIM-AG-704-01'],
    vcuCount: 1,
    vcuNumber: '20830',
    vcus: [
      { id: 'VCU-AG-704-1', number: '20830', position: 'Zentralmodul', status: 'offline' },
    ],
    modules: [
      { name: 'Connectivity Gateway', firmware: 'v4.9.0' },
    ],
    notes: 'Wird perspektivisch für Retrofit in die Pilotflotte aufgenommen.'
  },
];

/**
 * Filterbare Fahrzeugliste
 */
function getVehicles(filters = {}) {
  const { operator, status, country, search } = filters;

  return vehicles.filter(v => {
    if (operator && v.operator !== operator) return false;
    if (status && v.status !== status) return false;
    if (country && v.country !== country) return false;

    if (search && search.trim()) {
      const term = search.toLowerCase();
      const text = [
        v.id,
        v.name,
        String(v.shortNumber),
        v.fleet,
        v.operator,
        v.line,
        v.location,
        v.notes,
      ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();

      if (!text.includes(term)) return false;
    }

    return true;
  });
}

/**
 * Einzelnes Fahrzeug anhand der ID
 */
function getVehicleById(id) {
  return vehicles.find(v => v.id === id) || null;
}

module.exports = {
  vehicles,
  getVehicles,
  getVehicleById,
};
